apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-mysql
  labels:
    app: example-app
    name: simple-webapp-mysql
spec:
  selector:
    matchLabels:
      app: example-app
      name: simple-webapp-mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: example-app
        name: simple-webapp-mysql
    spec:
      containers:
       - name: simple-webapp-mysql
         image: 627483140334.dkr.ecr.us-east-1.amazonaws.com/clo835:7850fa60b7c883dfab8deee705e889855a5420be
         ports:
         - containerPort: 8080
         envFrom:
          - secretRef:
             name: app-secret
          - configMapRef: 
             name: config-bgimage
    
